stages:
- name: build
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: pip install -r requirements.txt
  - runScriptConfig:
      image: python:latest
      shellScript: pyhon start.py
timeout: 60
notification: {}
